"""Fetch and parse YouTube caption tracks into plain transcript text.

The studio-first scheduler uses the transcript of a Private draft to
generate a title via Claude. YouTube exposes two kinds of caption tracks:

  * `trackKind="standard"` — uploader-provided (manual) captions.
  * `trackKind="asr"`      — auto-generated by YouTube's speech recognizer.
    For recent uploads these are often missing or still processing; the
    scheduler treats "no transcript available" as "skip this draft and
    retry on the next run."

This module contains two public surfaces:

  * `fetch_transcript(client, video_id, *, quota)` — picks the best track,
    downloads its VTT body, parses it to plain text, and returns a
    `FetchedTranscript`. Returns `None` on any failure (missing track,
    403 from the download endpoint, empty body). Charges the quota tracker
    so the scheduler's accounting stays centralized.
  * `_parse_vtt(text)` — pure VTT-to-plain-text parser. Module-private so
    the unit tests can exercise it without a YouTube client.

Quota cost reference (per video):
  captions.list      50  (paid unconditionally once the list call runs)
  captions.download 200  (only paid on a successful download)

See `core.youtube_studio_scheduler` for how these fold into the per-run
quota math.
"""

from __future__ import annotations

import html
import logging
import re
from dataclasses import dataclass
from typing import TYPE_CHECKING, Protocol

from core.exceptions import PlatformAPIError, PlatformAuthError

if TYPE_CHECKING:
    from core.youtube_studio_scheduler import QuotaTracker

logger = logging.getLogger(__name__)

# Keep transcripts bounded. Claude doesn't need the full hour to title a
# short clip, and capping here makes prompt cost predictable. 8000 chars is
# ~2k tokens — comfortably under any model's context window but still long
# enough to capture the opening + core of a typical long clip.
_MAX_TRANSCRIPT_CHARS = 8000

# VTT syntax we strip. `NOTE` blocks span from `NOTE ...` up to the next
# blank line. Cue identifiers are lines that appear just before a timestamp
# line — we drop any line that's pure digits or a short kebab-case id.
_TIMESTAMP_RE = re.compile(r"-->")
_CUE_ID_RE = re.compile(r"^[\w.-]+$")  # no whitespace; letters/digits/_-. only
_INLINE_TAG_RE = re.compile(r"<[^>]+>")


@dataclass(frozen=True)
class FetchedTranscript:
    """Plain-text transcript plus the source track's kind ("standard"/"asr")."""

    text: str
    track_kind: str


class _CaptionClient(Protocol):
    """Structural interface so tests can pass a lightweight double."""

    def list_caption_tracks(self, video_id: str): ...
    def download_caption(self, track_id: str) -> str: ...


def fetch_transcript(
    client: _CaptionClient,
    video_id: str,
    *,
    quota: "QuotaTracker | None" = None,
) -> FetchedTranscript | None:
    """Return the best-available transcript for a video, or None.

    Track preference order: English standard > any standard > English ASR >
    any ASR > any track. This favors uploader-provided captions over
    machine-generated ones, and English over other languages (the Hormozi
    Highlights channel is English-only).

    `quota` (optional) is charged:
      * `_COST_LIST_CAPTIONS` (50) unconditionally after the list call,
        since YouTube bills us whether the list came back populated or not.
      * `_COST_DOWNLOAD_CAPTION` (200) only after a successful download.

    Swallows 403 and timeout errors on both calls (common when the token
    lacks `youtube.force-ssl` or ASR is still processing) and returns None.
    """
    # Import here to avoid a circular import — the scheduler module is the
    # owner of the cost constants and the QuotaTracker class.
    from core.youtube_studio_scheduler import (
        _COST_DOWNLOAD_CAPTION,
        _COST_LIST_CAPTIONS,
    )

    try:
        tracks = client.list_caption_tracks(video_id)
    except (PlatformAPIError, PlatformAuthError) as exc:
        logger.info("captions.list failed for %s: %s", video_id, exc)
        return None
    finally:
        if quota is not None:
            quota.charge(_COST_LIST_CAPTIONS, reason=f"captions.list {video_id}")

    if not tracks:
        return None

    chosen = _pick_track(tracks)
    if chosen is None:  # unreachable given _pick_track's fallbacks, but be safe
        return None

    try:
        raw = client.download_caption(chosen.id)
    except (PlatformAPIError, PlatformAuthError) as exc:
        logger.info("captions.download failed for %s track %s: %s", video_id, chosen.id, exc)
        return None

    if quota is not None:
        quota.charge(_COST_DOWNLOAD_CAPTION, reason=f"captions.download {video_id}")

    text = _parse_vtt(raw)
    if not text:
        return None

    if len(text) > _MAX_TRANSCRIPT_CHARS:
        text = text[:_MAX_TRANSCRIPT_CHARS]

    return FetchedTranscript(text=text, track_kind=chosen.track_kind)


def _pick_track(tracks):
    """Pick the most useful caption track from a list.

    Order: standard+en → standard (any lang) → asr+en → asr (any lang) →
    first track. Falls through cleanly on missing attributes.
    """
    def is_en(t) -> bool:
        return (t.language or "").lower().startswith("en")

    for t in tracks:
        if t.track_kind == "standard" and is_en(t):
            return t
    for t in tracks:
        if t.track_kind == "standard":
            return t
    for t in tracks:
        if t.track_kind == "asr" and is_en(t):
            return t
    for t in tracks:
        if t.track_kind == "asr":
            return t
    return tracks[0] if tracks else None


def _parse_vtt(text: str) -> str:
    """Convert a WEBVTT caption file body to a single plain-text string.

    Handles:
      * `WEBVTT` header + its `Kind:`/`Language:` metadata block.
      * `NOTE ...` blocks (skipped entirely, up to the next blank line).
      * Cue identifier lines (`1`, `cue-42`, etc.) that sit on their own
        line just before a timestamp line.
      * Timestamp lines (contain `-->`).
      * Inline HTML-ish tags (`<c>`, `<00:00:01.500>`, `<i>`, karaoke
        timestamps) — stripped with a plain regex.
      * HTML entities (`&amp;`, `&#39;`, `&quot;`) — decoded.
      * Adjacent duplicate lines (YouTube ASR emits each line twice across
        rolling cues) — deduped.

    Returns the joined, whitespace-collapsed result. Empty string on empty
    input or a file with no cue content.
    """
    if not text:
        return ""

    lines = text.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    i = 0

    # Skip WEBVTT header and any header-metadata lines up to the first blank.
    if lines and lines[0].strip().upper().startswith("WEBVTT"):
        i = 1
        while i < len(lines) and lines[i].strip() != "":
            i += 1

    kept: list[str] = []
    prev_clean: str | None = None

    while i < len(lines):
        raw = lines[i]
        stripped = raw.strip()

        # Skip blank separators.
        if stripped == "":
            i += 1
            continue

        # Skip NOTE blocks (NOTE through next blank line).
        if stripped == "NOTE" or stripped.startswith("NOTE "):
            i += 1
            while i < len(lines) and lines[i].strip() != "":
                i += 1
            continue

        # Skip timestamp lines.
        if _TIMESTAMP_RE.search(stripped):
            i += 1
            continue

        # Skip a cue identifier line — a non-whitespace token followed by a
        # timestamp line on the next non-blank row. Only fires when the next
        # real line actually contains `-->`, so we don't eat real text that
        # happens to be a single word.
        if _CUE_ID_RE.match(stripped):
            j = i + 1
            while j < len(lines) and lines[j].strip() == "":
                j += 1
            if j < len(lines) and _TIMESTAMP_RE.search(lines[j]):
                i += 1
                continue

        # Otherwise this is cue text. Strip inline tags + entities.
        cleaned = _INLINE_TAG_RE.sub("", stripped)
        cleaned = html.unescape(cleaned)
        cleaned = re.sub(r"\s+", " ", cleaned).strip()

        if cleaned and cleaned != prev_clean:
            kept.append(cleaned)
            prev_clean = cleaned

        i += 1

    return " ".join(kept).strip()
