/**
 * Ad Carousels Page
 *
 * Manually-triggered permutation factory:
 *   1. Build the bank (once, rerunnable): Claude filters the whole
 *      master tweet bank against your brief (e.g. entrepreneurship /
 *      entrepreneur mindset) into the ads_bank table.
 *   2. Generate batches: pick how many carousels you want (e.g. 100) —
 *      each is 7 random bank tweets + your CTA as the last slide (8 cards),
 *      guaranteed to differ from every carousel ever generated by at
 *      least 3 tweets (the ads_carousels ledger remembers all of them),
 *      exported as numbered folders in Google Drive.
 */

import { getSupabaseClient } from "@/lib/supabase";
import { AppShell } from "@/components/app-shell";
import { DetailPageHeader } from "@/components/command-center/detail-page-header";
import { ImagesIcon } from "lucide-react";
import { AdsCarouselCard } from "./ads-carousel-card";
import type { PathwayLastRun } from "@/components/pathway-card";

export const dynamic = "force-dynamic";

async function getLastRun(): Promise<PathwayLastRun | null> {
  const supabase = getSupabaseClient();
  const { data } = await supabase
    .from("cron_runs")
    .select("status, started_at, posts_processed")
    .eq("platform", "ads")
    .in("job_type", ["ads_carousel", "ads_bank_build"])
    .order("started_at", { ascending: false })
    .limit(1);
  const row = data?.[0];
  if (!row) return null;
  return {
    status: row.status as PathwayLastRun["status"],
    startedAt: row.started_at as string,
    count: (row.posts_processed as number | null) ?? 0,
  };
}

// head:true count queries — no rows transferred, just the totals for the
// header stats and the card's capacity readouts.
async function getCounts(): Promise<{ bankSize: number; totalPermutations: number }> {
  const supabase = getSupabaseClient();
  const [bank, ledger] = await Promise.all([
    supabase.from("ads_bank").select("*", { count: "exact", head: true }),
    supabase.from("ads_carousels").select("*", { count: "exact", head: true }),
  ]);
  return {
    bankSize: bank.count ?? 0,
    totalPermutations: ledger.count ?? 0,
  };
}

async function getSettings(): Promise<{ defaultPrompt: string; ctaText: string }> {
  const supabase = getSupabaseClient();
  const { data } = await supabase
    .from("ads_carousel_settings")
    .select("default_prompt, cta_text")
    .eq("id", 1)
    .single();
  return {
    defaultPrompt: (data?.default_prompt as string | null) ?? "",
    ctaText: (data?.cta_text as string | null) ?? "",
  };
}

export default async function AdsCarouselsPage() {
  const [lastRun, { bankSize, totalPermutations }, settings] = await Promise.all([
    getLastRun(),
    getCounts(),
    getSettings(),
  ]);

  return (
    <AppShell>
      <div className="cc-reveal">
        <DetailPageHeader
          // No PlatformIcon exists for "ads" (it's not a social platform) —
          // a lucide glyph stands in.
          icon={<ImagesIcon className="size-8" style={{ color: "#D76E9A" }} />}
          eyebrow="Ads · Graphics"
          title="Ad Carousels"
          subtitle="Non-repeating tweet-carousel permutations, exported to Google Drive"
          accent="#D76E9A"
          stats={[
            { label: "Bank tweets", value: bankSize },
            { label: "Permutations made", value: totalPermutations },
          ]}
          backHref="/"
          backLabel="Command Center"
        />
      </div>

      <div className="mb-4 mt-7 cc-reveal" style={{ animationDelay: "0.06s" }}>
        {/* Pipeline metadata strip */}
        <div className="cc-surface mb-5 px-4 py-3 text-xs text-white/65">
          <div className="flex flex-wrap gap-x-6 gap-y-1.5">
            <span>
              <span className="text-white/40">Schedule</span>{" "}
              <span className="font-mono">Manual — build bank once, then generate batches</span>
            </span>
            <span>
              <span className="text-white/40">Repeat rule</span>{" "}
              <span className="font-mono">every carousel differs by ≥ 3 tweets</span>
            </span>
            <span>
              <span className="text-white/40">Renderer</span>{" "}
              <span className="font-mono">1080×1350 ads template</span>
            </span>
            <span>
              <span className="text-white/40">Output</span>{" "}
              <span className="font-mono">Drive folder per carousel</span>
            </span>
          </div>
        </div>
      </div>

      <div className="cc-reveal" style={{ animationDelay: "0.12s" }}>
        <AdsCarouselCard
          settings={settings}
          bankSize={bankSize}
          totalPermutations={totalPermutations}
          lastRun={lastRun}
        />
      </div>
    </AppShell>
  );
}
